source_address: 127.0.0.1
source_database: opd_couchdb_dhis_development
source_username : root
source_password : sam
source_port : 5984

#not being used  sofar
dest_host : 192.168.18.243
dest_port : 5984
dest_username : root
dest_password : sam
dest_database : opd_couchdb_dhis_development
