development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: opd_couchdb_dhis
  suffix: development
  username: root
  password: sam

test:
  <<: *development
  suffix: test

production:
  protocol: 'https'
  host: localhost
  port: 5984
  prefix: opd_couchdb_dhis
  suffix: production
  username: root
  password: sam
